version: '3.8'

services: 
    api-service:
        container_name: api
        build: ./api/
        volumes: 
            - ./api/:/usr/src/app/
        ports:
            - ${API_PORT}:${API_PORT}
        env_file:
            - .env
        depends_on:
            - influxdb
        links:
            - influxdb

    influxdb:
        image: influxdb:latest
        container_name: influxdb
        expose:
            - ${DB_PORT}
        volumes:
            - influxdb-storage:/var/lib/influxdb
        environment: 
            INFLUXDB_CONTINUOUS_QUERIES_ENABLED: 1
            INFLUXDB_CONTINUOUS_QUERIES_RUN_INTERVAL: 30s
            INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED: 1
            # INFLUXDB_ADMIN_USER: admin
            # INFLUXDB_ADMIN_PASSWORD: Welcome1 
            
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: always
        ports:
            - ${GRAFANA_PORT}:${GRAFANA_PORT}
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./grafana-provisioning/:/etc/grafana/provisioning
        depends_on:
            - influxdb


volumes:
    influxdb-storage:
        name: influxdb-storage
    grafana-storage:
        name: grafana-storage





        
        
