version: '3.8'

services: 
    api-service:
        container_name: api
        build: ./api/
        volumes: 
            - ./api/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            API_PORT: 5000
            DB_PORT: "8086"
            PYTHONPATH: ./api/:/usr/src/app/
            DB_HOST: "influxdb"
        depends_on:
            - influxdb
        links:
            - influxdb

    influxdb:
        build: ./influxdb/
        expose:
            - "8086"
        volumes:
            - './influxdb/:/var/lib/influxdb'
            
    chronograf:
        image: chronograf:latest
        ports:
        - '127.0.0.1:8888:8888'
        volumes:
        - chronograf-storage:/var/lib/chronograf
        depends_on:
        - influxdb
        environment:
            INFLUXDB_URL: http://influxdb:8086
volumes:
  chronograf-storage:


        
        
