version: '3.8'

services: 
    api-service:
        container_name: api
        build: ./api/
        volumes: 
            - ./api/:/usr/src/app/
        ports:
            - ${API_PORT}:${API_PORT}
        environment: 
            API_PORT: ${API_PORT}
            DB_PORT: ${DB_PORT}
            PYTHONPATH: ./api/:/usr/src/app/
            DB_HOST: ${DB_HOST}
        depends_on:
            - influxdb
        links:
            - influxdb

    influxdb:
        image: influxdb:latest
        container_name: influxdb
        expose:
            - ${DB_PORT}
        volumes:
            - influxdb-storage:/var/lib/influxdb
        environment: 
            INFLUXDB_CONTINUOUS_QUERIES_ENABLED: 1
            INFLUXDB_CONTINUOUS_QUERIES_RUN_INTERVAL: 30s
            INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED: 1
            # INFLUXDB_ADMIN_USER: admin
            # INFLUXDB_ADMIN_PASSWORD: Welcome1 
            
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./grafana-provisioning/:/etc/grafana/provisioning
        depends_on:
            - influxdb
        # environment:
        #     - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
        #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
    influxdb-storage:
        name: influxdb-storage
    grafana-storage:
        name: grafana-storage





        
        
