version: '3.8'


services: 
    api-service:
        build: ./api-predictor/
        volumes: 
            - ./api-predictor/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
        depends_on:
            - influxdb
        links:
            - influxdb

    influxdb:
        build: ./influx/
        expose:
            - "8086"
        volumes:
            - './influx/:/var/lib/influxdb'



        
        