version: '3.8'

services: 
    api-service:
        container_name: api
        build: ./api/
        volumes: 
            - ./api/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            PYTHONPATH: ./api/:/usr/src/app/
        depends_on:
            - influxdb
        links:
            - influxdb

    influxdb:
        build: ./influxdb/
        expose:
            - "8086"
        volumes:
            - './influxdb/:/var/lib/influxdb'



        
        
