version: '3.8'

services: 
    api-service:
        container_name: api
        build: ./api/
        volumes: 
            - ./api/:/usr/src/app/
        ports:
            - ${API_PORT}:${API_PORT}
        environment: 
            API_PORT: ${API_PORT}
            DB_PORT: ${DB_PORT}
            PYTHONPATH: ./api/:/usr/src/app/
            DB_HOST: ${DB_HOST}
        depends_on:
            - influxdb
        links:
            - influxdb

    influxdb:
        image: influxdb
        expose:
            - ${DB_PORT}
        volumes:
            - influxdb-storage:/var/lib/influxdb
        environment: 
            INFLUXDB_CONTINUOUS_QUERIES_ENABLED: 1
            INFLUXDB_CONTINUOUS_QUERIES_RUN_INTERVAL: 30s
            INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED: 1
            
    chronograf:
        image: chronograf:latest
        ports:
        - ${CHRONOGRAF_PORT}:${CHRONOGRAF_PORT}
        volumes:
        - chronograf-storage:/var/lib/chronograf
        depends_on:
        - influxdb
        environment:
            INFLUXDB_URL: http://${DB_HOST}:${DB_PORT}

volumes:
    chronograf-storage:
        name: chronograf-storage
    influxdb-storage:
        name: influxdb-storage





        
        
