name: dissertation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - pandas=1.1.3
  - numpy=1.19.1
  - scikit-learn=0.23.2
  - statsmodels=0.12.0
  - flasgger=0.9.1
  - marshmallow
  - apispec=0.39.0
  - flask
  - matplotlib
  - jupyter
  - flask-marshmallow

